import type { Metadata } from "next";
import {
  Plus_Jakarta_Sans,
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  Doto,
  Sixtyfour_Convergence,
} from "next/font/google";
import "./globals.css";
import { FooterSection } from "@/components/Footer";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Nav } from "@/components/Nav";
import { Toaster } from "@/components/ui/sonner";

import { Analytics } from "@vercel/analytics/next";

const fontFamily = Plus_Jakarta_Sans({
  variable: "--font-main",
  subsets: ["latin"],
});

const fontMono = Sixtyfour_Convergence({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hip Hop Western",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontMono.variable} ${fontFamily.variable} antialiased`}
      >
        {children}
        <Toaster position="bottom-center" />
        <FooterSection />
        <Analytics />
      </body>
    </html>
  );
}
